import type { NextRequest } from "next/server";
import { getLoginSecurityContext } from "@/lib/login-security";

type EmailAlertEvent = "LOGIN" | "PASSWORD_SETUP" | "FAILED_LOGIN_THRESHOLD";

type EmailAlertOptions = {
  failedAttemptCount?: number;
  windowMinutes?: number;
};

type EmailAlertResult =
  | { sent: true; id?: string }
  | { sent: false; reason: "not-configured" | "failed" };

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function alertContent(
  request: NextRequest,
  event: EmailAlertEvent,
  options: EmailAlertOptions,
) {
  const context = getLoginSecurityContext(request);
  const timestamp = new Intl.DateTimeFormat("en-US", {
    dateStyle: "full",
    timeStyle: "long",
    timeZone: "America/New_York",
  }).format(new Date());
  const failure = event === "FAILED_LOGIN_THRESHOLD";
  const title = failure
    ? "Repeated failed login attempts detected"
    : "Portfolio Tracker security alert";
  const eventText =
    event === "PASSWORD_SETUP"
      ? "Portfolio password created successfully"
      : event === "LOGIN"
        ? "Portfolio sign-in completed successfully"
        : `${options.failedAttemptCount || 4} failed password attempts from the same public IP within the last ${options.windowMinutes || 15} minutes`;
  const fields: Array<[string, string]> = [
    ["Event", eventText],
    ["Time", `${timestamp} (America/New_York)`],
    ["Public client IP", context.publicIp],
    ["Forwarded IP chain", context.forwardedFor],
    ["Cloudflare client IP", context.cloudflareIp],
    ["Reverse-proxy IP", context.realIp],
    ["Browser / user agent", context.userAgent],
    ["Browser client hints", context.browserHints],
    ["Browser platform", context.browserPlatform],
    ["Mobile client hint", context.mobileHint],
    ["Language preferences", context.acceptLanguage],
    ["Requested host", context.host],
    ["Forwarded host / protocol", `${context.forwardedHost} / ${context.forwardedProto}`],
    ["Origin / referrer", `${context.origin} / ${context.referer}`],
    ["Machine hostname", context.machineName],
    ["Client local/LAN IP", context.localNetworkIp],
  ];
  const text = [title, "", ...fields.map(([label, value]) => `${label}: ${value}`)].join("\n");
  const rows = fields
    .map(
      ([label, value]) =>
        `<tr><td style="padding:8px 12px;border:1px solid #dbe4ea;background:#f8fafc;font-weight:700;vertical-align:top">${escapeHtml(label)}</td><td style="padding:8px 12px;border:1px solid #dbe4ea;word-break:break-word">${escapeHtml(value)}</td></tr>`,
    )
    .join("");
  const html = `<div style="font-family:Arial,sans-serif;color:#1e293b;max-width:720px"><h2 style="margin:0 0 12px;color:${failure ? "#b91c1c" : "#0b7041"}">${escapeHtml(title)}</h2><p style="margin:0 0 16px;color:#475569">This notification is generated by Portfolio Tracker.</p><table style="border-collapse:collapse;width:100%;font-size:14px">${rows}</table><p style="margin:16px 0 0;font-size:12px;color:#64748b">Browser security policies intentionally prevent websites from reading a device hostname or private LAN IP. The values above explicitly show when that information is unavailable.</p></div>`;
  return { title, text, html };
}

/**
 * Sends a best-effort email security alert via Resend's REST API. It is a no-op
 * until all required server-side environment variables are configured and never
 * blocks successful setup, login, or failed-login error handling.
 */
export async function sendEmailLoginAlert(
  request: NextRequest,
  event: EmailAlertEvent,
  options: EmailAlertOptions = {},
): Promise<EmailAlertResult> {
  const apiKey = process.env.RESEND_API_KEY?.trim();
  const to = process.env.LOGIN_ALERT_EMAIL_TO?.trim();
  const from = process.env.LOGIN_ALERT_EMAIL_FROM?.trim();
  if (!apiKey || !to || !from) {
    return { sent: false, reason: "not-configured" };
  }

  const content = alertContent(request, event, options);
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8_000);
  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [to],
        subject: content.title,
        text: content.text,
        html: content.html,
        tags: [{ name: "event", value: `portfolio-${event.toLowerCase()}` }],
      }),
      signal: controller.signal,
      cache: "no-store",
    });
    const payload = (await response.json().catch(() => null)) as
      | { id?: string; message?: string; name?: string }
      | null;
    if (!response.ok) {
      console.warn("Email login alert was not sent", {
        status: response.status,
        error: payload?.message || payload?.name || "provider rejected request",
      });
      return { sent: false, reason: "failed" };
    }
    return { sent: true, id: payload?.id };
  } catch (error) {
    console.warn("Email login alert request failed", {
      reason:
        error instanceof Error && error.name === "AbortError"
          ? "timed out"
          : "network error",
    });
    return { sent: false, reason: "failed" };
  } finally {
    clearTimeout(timeout);
  }
}
